// src/constants/tagKeys.js
export const TAG_KEYS = {
  ADDRESS: "Address",
  AUTH: "Auth",
  BRANCHES: "Branches",
  CART: "Cart",
  CATEGORIES: "Categories",
  COLOR: "Color",
  DISTRICT: "District",
  ORDER: "Order",
  PRODUCT: "Product",
  PRODUCT_VARIANT: "Product_Variant",
  PROMOTION: "Promotion",
  PROVINCE: "Province",
  REVIEW: "Review",
  ROLE: "Role",
  SIZE: "Size",
  USER: "User",
  WARD: "Ward",
};
